d=open('hesco_ov.png','rb').read()
o=open('app/src/main/cpp/Panel/Fonts/Bytes/BytesImg.hpp','w')
o.write('#pragma once\n\n')
o.write('const int LogoWidth = 720;\n')
o.write('const int LogoHeight = 1600;\n\n')
o.write('const unsigned char LogoMenuRawRGBA[] = {\n')
for i,b in enumerate(d):
    if i%16==0: o.write('    ')
    o.write('0x%02X, '%b)
    if i%16==15: o.write('\n')
o.write('\n};\n')
o.write('const size_t LogoMenuRawRGBASize = %d;\n'%len(d))
o.close()
print('Done:',len(d))
